### ISSUE TITLE
elgg search fails due to private profiles in 2.3

### ISSUE THREAD

**Issue by propertunist** [iionly/private_profiles#5]
on both my live and development site i am seeing fatal errors when searching for tags. basically i just click a tag in the site and i see a crash relating to private profiles - which stops when i disable private profiles. this only occurs when i am logged out.
```
2017/04/07 00:04:01 [error] 1518#0: *25231 FastCGI sent in stderr: "PHP message: Exception at time 1491519841: DatabaseException: An exception occurred while executing 

SELECT COUNT(DISTINCT e.guid) as total 
FROM entities e  
JOIN metadata md on e.guid = md.entity_guid  
JOIN metastrings msn on md.name_id = msn.id  
JOIN metastrings msv on md.value_id = msv.id  
WHERE  (
    msn.string IN ("tags","location","interests") 
	AND msv.string = 'voluptatem' 
	AND (
        (md.access_id IN (2,-5)) 
		AND (
            md.enabled = 'yes' 
    		AND NOT EXISTS (
				SELECT 1 FROM private_settings
				WHERE entity_guid IN (md.guid, md.owner_guid)
				AND name = 'plugin:user_setting:private_profiles:user_activity_setting'
				AND value = 'members'
			)
		)
	)
)
AND  (e.site_guid IN (1)) 
AND (
    (e.access_id IN (2,-5)) 
	AND (
        e.enabled = 'yes' 
        AND NOT EXISTS (
			SELECT 1 FROM private_settings
			WHERE
			entity_guid IN (e.guid, e.owner_guid)
			AND name = 'plugin:user_setting:private_profiles:user_activity_setting'
			AND value = 'members'
		)
	)
);

SQLSTATE[42S22]: Column not found: 1054 Unknown col" while reading response header from upstream, client: 127.0.0.1, server: mysite.org, request: "GET /search?q=voluptatem&search_type=tags HTTP/1.1"
```

**Comment by propertunist** [comment]
i just ran the query against the database manually and i now see the additional info:
```
 Unknown column 'md.guid' in 'where clause' 
```
though i don't know which reference to this field is the problem

**Comment by propertunist** [comment]
ah, the error relates to the line:
```
md.enabled = 'yes'
```

**Comment by propertunist** [comment]
and now for some reason it relates to md.guid

**Comment by propertunist** [comment]
oh, so i just found the function applyActivityPrivacy
in your code which is a hook that handles 'get_sql' and adds in your extra AND clause.

**Comment by propertunist** [comment]
so, in summary - somehow your hook is being passed a reference to the metadata table and a field in that table called 'guid', except there is no guid field in the metadata table, instead there is only an 'id' field. i don't yet understand what is causing this inconsistency.

**Comment by iionly** [comment]
The query code applyActivityPrivacy should get "appended" to the original query. With Elgg API functions used for a query this works fine. But I already came across basically the same problem with the query code used in the Event Calendar plugin that used a custom query code for retrieving the event entities instead of using elgg_get_entities_from_metadata(). I've rewritten the code in Event Calendar and this solved the issue (not yet been able to release a new version as more issues pop up as soon as I think I'm done...).

But I thought that Elgg core wouldn't use any custom code queries. But this thought seems to have been wrong. As it says in the search plugin code in a comment:

"don't use elgg_get_entities_from_metadata() here because of performance issues"

Bummer!

Maybe it's necessary to fix this problem to open an issue in the Elgg core repo, too, to discuss the options. With the Elgg core code in the search plugin changed and no longer a custom query being made the problem wouldn't occur anymore. I don't know if the custom "and" query in the Private Profiles plugin could get modified to prevent an error with custom queries being made. The commits that added this functionality (hiding activity from logged-out visitors) were made by @hypeJunction. Maybe there's some way of preventing the original query getting broken by the additional code regardless what the original query is. This would surely be the safer way to fix it as there could always be some custom query being used by some 3rd party plugin.

**Comment by iionly** [comment]
Issue will be fixed in Elgg core by https://github.com/Elgg/Elgg/pull/10885.
